version: "3"
services:
    # mqtt5 eclipse-mosquitto
    mqtt5:
      image: eclipse-mosquitto
      container_name: mqtt5
      ports:
        - 1883:1883 #default mqtt port
        - 9001:9001 #default mqtt port for websockets
      volumes:
        - ./config:/mosquitto/config
        - ./data:/mosquitto/data
        - ./log:/mosquitto/log:rw
    #
